### ISSUE TITLE
Per our own best practices, should we update build.psd1?

### ISSUE THREAD

**Issue by Jaykul** [questionmark/PowerShellTemplate#5]
I think we want to add the `OutputDirectory` and `VersionedOutputDirectory` values

**Comment by JPRuskin** [comment]
After moving the source into a /source folder, it seems to work with just adding VersionedOutputDirectory.

**Comment by Jaykul** [comment]
Good enough, I guess. I've been toying with the idea of building into `./Output` but for that, I think I need the Build module to support that as an option PoshCode/ModuleBuilder/issues/65

**Comment by Jaykul** [comment]
I think with ModuleBuilder 2.0 we don't need the `VersionedOutputDirectory` but I'd personally rather use `OutputDirectory = '..'` if we put the source in `source`
